name: Scan Repository for Vulnerabilities

on:
  workflow_dispatch:
    inputs:
      scan_path:
        description: 'Path to scan (default: .)'
        required: false
        default: '.'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan dependencies for vulnerabilities
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          scan-ref: .
          format: 'template'  # oder 'json' für eine andere Ausgabe
          template: '@./trivy-html-report-template.tpl'
          output: 'trivy-scan.html'

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-scan.html

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [scan]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Download Trivy Report
        uses: actions/download-artifact@v4
        with:
          name: trivy-scan-report

      - name: Deploy Trivy Report to Webserver
        run: scp trivy-scan.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/group6/cev_scan_michi.html
