name: Scan Repository for Vulnerabilities

on:
  workflow_dispatch:
    inputs:
      scan_path:
        description: 'Path to scan (default: .)'
        required: false
        default: '.'

jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin
          ./bin/trivy --version

      # Run Trivy to scan the repository for vulnerabilities
      - name: Scan Repository for Vulnerabilities
        run: |
          ./bin/trivy fs --security-checks vuln,secret ${{ github.event.inputs.scan_path }}
